title: "Adapting Visual Foundation Models"
description: "Mario Koddenbrock"
#remote_theme: pages-themes/architect@v0.2.0
#remote_theme: pages-themes/minimal@v0.2.0
#remote_theme: pages-themes/hacker@v0.2.0
remote_theme: pages-themes/cayman@v0.2.0