title: "Adapting Visual Foundation Models"
author: "Mario Koddenbrock"
description: "Mario Koddenbrock"
remote_theme: samarsault/plainwhite-jekyll

# Recommended settings for the plainwhite-jekyll theme
plainwhite:
  navigation: # Add links to a top navigation bar
    - title: About
      url: /
    - title: Publications
      url: /
  social: # Add social media links to the footer
    - icon: github
      url: https://github.com/mario-koddenbrock
    - icon: linkedin
      url: https://www.linkedin.com/in/koddenbrock/
    - icon: "google-scholar" # Custom icon
      url: https://scholar.google.com/citations?user=wqHic0AAAAAJ&hl=de

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag